import { MaterialCommunityIcons } from "@expo/vector-icons";
import * as ImagePicker from "expo-image-picker";
import * as Notifications from "expo-notifications";
import * as Speech from "expo-speech";
import React, { useEffect, useState } from "react";
import { Alert, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { useTheme } from "../../context/ThemeContext";
import { useI18n } from "../../i18n";
import { getLiveMarketPrices } from "../../lib/spring-api";
import { loadOfflineEntities, loadSyncQueue, markQueueSynced, removeOfflineEntity, saveOfflineEntity, type OfflineEntity } from "../../lib/offline-store";
import { ScreenHeader } from "@/components/ui/ScreenHeader";

type ToolKey = "calendar" | "alerts" | "finance" | "inventory" | "marketplace" | "best-market" | "disease" | "assistant" | "fields" | "planting" | "soil-inputs" | "offers" | "orders" | "analytics" | "equipment" | "labour";
const TOOLS: { key: ToolKey; title: string; subtitle: string; icon: keyof typeof MaterialCommunityIcons.glyphMap }[] = [
  { key: "calendar", title: "Crop calendar", subtitle: "Tasks and reminders", icon: "calendar-check" },
  { key: "alerts", title: "Smart alerts", subtitle: "Weather and prices", icon: "bell-ring-outline" },
  { key: "finance", title: "Farm finance", subtitle: "Expenses and profit", icon: "calculator-variant-outline" },
  { key: "inventory", title: "Harvest inventory", subtitle: "Quantity and readiness", icon: "warehouse" },
  { key: "marketplace", title: "Marketplace", subtitle: "Listings and buyer chat", icon: "storefront-outline" },
  { key: "best-market", title: "Best market", subtitle: "Compare current prices", icon: "map-marker-star" },
  { key: "disease", title: "Disease screening", subtitle: "Photo and symptoms", icon: "leaf-circle-outline" },
  { key: "assistant", title: "Voice assistant", subtitle: "Spoken farm guidance", icon: "microphone-outline" },
  { key: "fields", title: "Field management", subtitle: "Land, soil and irrigation", icon: "map-marker-radius-outline" },
  { key: "planting", title: "Crop-cycle records", subtitle: "Planting, harvest and tasks", icon: "sprout-outline" },
  { key: "soil-inputs", title: "Soil & inputs", subtitle: "Tests, fertilizer and chemicals", icon: "flask-outline" },
  { key: "offers", title: "Buyer offers", subtitle: "Compare and negotiate offers", icon: "handshake-outline" },
  { key: "orders", title: "Orders & payments", subtitle: "Delivery and balance tracking", icon: "truck-delivery-outline" },
  { key: "analytics", title: "Farm analytics", subtitle: "Costs, revenue and yield", icon: "chart-box-outline" },
  { key: "equipment", title: "Equipment", subtitle: "Maintenance and fuel costs", icon: "tractor-variant" },
  { key: "labour", title: "Labour records", subtitle: "Tasks, attendance and wages", icon: "account-hard-hat-outline" },
];

export function FarmToolkitScreen({ onBack }: { onBack: () => void }) {
  const { theme } = useTheme(); const { colors } = theme; const { language } = useI18n();
  const [active, setActive] = useState<ToolKey | null>(null); const [entities, setEntities] = useState<OfflineEntity[]>([]); const [queued, setQueued] = useState(0);
  const reload = async () => { setEntities(await loadOfflineEntities()); setQueued((await loadSyncQueue()).length); };
  useEffect(() => { void reload(); }, []);
  const add = async (input: Parameters<typeof saveOfflineEntity>[0]) => { await saveOfflineEntity(input); await reload(); };
  const sync = async () => { setEntities(await markQueueSynced()); setQueued(0); Alert.alert("Synchronization", "Local changes are marked as synchronized."); };
  const syncAction=<TouchableOpacity style={[styles.sync,{backgroundColor:colors.primarySoft}]} onPress={sync}><MaterialCommunityIcons name="sync" size={18} color={colors.primary}/><Text style={{color:colors.primary,fontWeight:"700"}}>Sync</Text></TouchableOpacity>;
  return <SafeAreaView edges={["top"]} style={[styles.safe,{backgroundColor:colors.background}]}><ScreenHeader title={active ? TOOLS.find(x=>x.key===active)?.title ?? "Farmer toolkit" : "Farmer toolkit"} subtitle={`${queued} offline change${queued===1?"":"s"} waiting`} icon="view-grid-outline" onBack={active ? ()=>setActive(null):onBack} action={syncAction}/>
    {!active ? <ScrollView contentContainerStyle={styles.content}><View style={[styles.offlineCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><MaterialCommunityIcons name="cloud-check-outline" size={27} color={colors.primary}/><View><Text style={[styles.cardTitle,{color:colors.text}]}>Offline-first farm records</Text><Text style={[styles.sub,{color:colors.textMuted}]}>Create records without internet and synchronize later.</Text></View></View><View style={styles.grid}>{TOOLS.map(tool=><TouchableOpacity key={tool.key} style={[styles.tool,{backgroundColor:colors.surface,borderColor:colors.border}]} onPress={()=>setActive(tool.key)}><View style={[styles.icon,{backgroundColor:colors.primarySoft}]}><MaterialCommunityIcons name={tool.icon} size={25} color={colors.primary}/></View><Text style={[styles.cardTitle,{color:colors.text}]}>{tool.title}</Text><Text style={[styles.sub,{color:colors.textMuted}]}>{tool.subtitle}</Text></TouchableOpacity>)}</View><Text style={[styles.sectionTitle,{color:colors.text}]}>Recent offline records</Text><EntityList entities={entities.slice(0,6)} onRemove={async id=>{await removeOfflineEntity(id);await reload();}} /></ScrollView> : <ToolBody tool={active} entities={entities} add={add} language={language} colors={colors}/>}</SafeAreaView>;
}

function ToolBody({tool,entities,add,language,colors}:{tool:ToolKey;entities:OfflineEntity[];add:(value:Parameters<typeof saveOfflineEntity>[0])=>Promise<void>;language:string;colors:ReturnType<typeof useTheme>["theme"]["colors"]}) {
  const [title,setTitle]=useState(""); const [detail,setDetail]=useState(""); const [amount,setAmount]=useState(""); const [quantity,setQuantity]=useState(""); const [date,setDate]=useState("");
  const [photo,setPhoto]=useState<string>(); const [result,setResult]=useState(""); const [marketResult,setMarketResult]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [question,setQuestion]=useState("");
  const byKind=(kind:OfflineEntity["kind"])=>entities.filter(x=>x.kind===kind);
  const revenue=byKind("inventory").reduce((s,x)=>s+(x.amount??0)*(x.quantity??0),0); const expenses=byKind("expense").reduce((s,x)=>s+(x.amount??0),0);
  const create=async(kind:OfflineEntity["kind"])=>{if(!title.trim())return;await add({kind,title:title.trim(),detail:detail.trim(),amount:Number(amount)||undefined,quantity:Number(quantity)||undefined,date:date||undefined});setTitle("");setDetail("");setAmount("");setQuantity("");setDate("");};
  if(tool==="best-market") return <ToolScroll colors={colors}><Info colors={colors} text="Recommendations compare published prices only. Confirm transport and handling costs before selling."/><PrimaryButton colors={colors} label={loading?"Comparing…":"Compare live HARTI markets"} onPress={async()=>{setLoading(true);try{const live=await getLiveMarketPrices();setMarketResult((live.entries??[]).slice(0,8).map(e=>`${e.cropName}: ${e.displayPrice}`));}catch{Alert.alert("Unavailable","Could not load live market prices.");}finally{setLoading(false);}}}/>{marketResult.map(x=><Card key={x} colors={colors}><Text style={{color:colors.text}}>{x}</Text></Card>)}</ToolScroll>;
  if(tool==="disease") return <ToolScroll colors={colors}><Info colors={colors} text="This is an early screening aid, not a laboratory diagnosis. Consult an agricultural officer before treatment."/>{photo&&<Image source={{uri:photo}} style={styles.photo}/>}<PrimaryButton colors={colors} label="Choose crop photo" onPress={async()=>{const value=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:.7});if(!value.canceled)setPhoto(value.assets[0].uri);}}/><Field colors={colors} placeholder="Describe spots, colour, wilting or insects" value={detail} onChange={setDetail}/><PrimaryButton colors={colors} label="Screen symptoms" onPress={()=>{if(!photo||!detail.trim())return;const d=detail.toLowerCase();setResult(d.includes("yellow")?"Possible nutrient stress or viral symptoms. Isolate affected plants and request an officer inspection.":d.includes("spot")||d.includes("brown")?"Possible fungal or bacterial leaf-spot symptoms. Avoid overhead watering and seek local diagnosis.":"Symptoms are not specific enough for a safe match. Capture both sides of the leaf and consult an agricultural officer.");}}/>{result&&<Card colors={colors}><Text style={[styles.cardTitle,{color:colors.text}]}>Screening result</Text><Text style={[styles.body,{color:colors.textSecondary}]}>{result}</Text></Card>}</ToolScroll>;
  if(tool==="assistant") return <ToolScroll colors={colors}><Info colors={colors} text="Ask in English, Sinhala, or Tamil. The response can be read aloud."/><Field colors={colors} placeholder="Ask a farming question" value={question} onChange={setQuestion}/><PrimaryButton colors={colors} label="Answer and speak" onPress={()=>{const answer=assistantAnswer(question,language);setResult(answer);Speech.speak(answer,{language:language==="si"?"si-LK":language==="ta"?"ta-LK":"en-US",rate:.88});}}/>{result&&<Card colors={colors}><Text style={[styles.body,{color:colors.text}]}>{result}</Text><TouchableOpacity onPress={()=>Speech.stop()}><Text style={{color:colors.primary,marginTop:10,fontWeight:"700"}}>Stop speaking</Text></TouchableOpacity></Card>}</ToolScroll>;
  if(tool==="analytics") {const harvestKg=byKind("inventory").reduce((s,x)=>s+(x.quantity??0),0);const labourCost=byKind("labour").reduce((s,x)=>s+(x.amount??0),0);const equipmentCost=byKind("equipment").reduce((s,x)=>s+(x.amount??0),0);const inputCost=byKind("input").reduce((s,x)=>s+(x.amount??0),0);const totalCost=expenses+labourCost+equipmentCost+inputCost;return <ToolScroll colors={colors}><Metric colors={colors} label="Recorded harvest" value={`${harvestKg.toLocaleString()} kg`}/><Metric colors={colors} label="Projected revenue" value={`Rs. ${revenue.toLocaleString()}`}/><Metric colors={colors} label="Total recorded cost" value={`Rs. ${totalCost.toLocaleString()}`}/><Metric colors={colors} label="Estimated profit" value={`Rs. ${(revenue-totalCost).toLocaleString()}`}/><Metric colors={colors} label="Active fields" value={`${byKind("field").length}`}/><Metric colors={colors} label="Crop cycles" value={`${byKind("planting").length}`}/><Info colors={colors} text="Analytics use the records stored on this device. Add harvest prices, quantities, expenses, inputs, labour and equipment costs for better results."/></ToolScroll>}
  const config = tool==="calendar"?{kind:"calendar" as const,button:"Add farm task",title:"Task or crop",detail:"Instructions",extra:"YYYY-MM-DD"}:tool==="alerts"?{kind:"alert" as const,button:"Save alert rule",title:"Crop or weather event",detail:"Condition, e.g. price above Rs. 500",extra:"Review date"}:tool==="finance"?{kind:"expense" as const,button:"Add expense",title:"Expense name",detail:"Supplier or notes",extra:"Date"}:tool==="inventory"?{kind:"inventory" as const,button:"Add harvest batch",title:"Crop and grade",detail:"Location or readiness",extra:"Harvest date"}:tool==="fields"?{kind:"field" as const,button:"Add field",title:"Field name",detail:"Area (ha), soil type, GPS/location and irrigation",extra:"Registration date"}:tool==="planting"?{kind:"planting" as const,button:"Save crop cycle & create tasks",title:"Crop and seed variety",detail:"Field, planting method and expected yield",extra:"Planting date"}:tool==="soil-inputs"?{kind:"input" as const,button:"Add soil/input record",title:"Soil test, fertilizer or chemical",detail:"pH/NPK, application rate and safety interval",extra:"Test/application date"}:tool==="offers"?{kind:"offer" as const,button:"Save buyer offer",title:"Buyer and crop",detail:"Offered price, pickup date and negotiation notes",extra:"Offer expiry"}:tool==="orders"?{kind:"farmer_order" as const,button:"Add order",title:"Buyer, crop and order number",detail:"Packing, pickup/delivery and payment status",extra:"Delivery date"}:tool==="equipment"?{kind:"equipment" as const,button:"Add equipment record",title:"Machine or equipment",detail:"Maintenance, fuel or availability notes",extra:"Service date"}:tool==="labour"?{kind:"labour" as const,button:"Add labour record",title:"Worker or team",detail:"Attendance and assigned task",extra:"Work date"}:{kind:tool==="marketplace"?"listing" as const:"message" as const,button:"Publish offline listing",title:"Crop listing",detail:"Quality, photos description, buyer message or pickup location",extra:"Available date"};
  const list=byKind(config.kind);
  const needsAmount=["finance","inventory","marketplace","soil-inputs","offers","orders","equipment","labour"].includes(tool);const needsQuantity=["inventory","marketplace","offers","orders"].includes(tool);
  return <ToolScroll colors={colors}>{tool==="finance"&&<View style={styles.summary}><Metric colors={colors} label="Projected revenue" value={`Rs. ${revenue.toLocaleString()}`}/><Metric colors={colors} label="Recorded expenses" value={`Rs. ${expenses.toLocaleString()}`}/><Metric colors={colors} label="Estimated profit" value={`Rs. ${(revenue-expenses).toLocaleString()}`}/></View>}<Field colors={colors} placeholder={config.title} value={title} onChange={setTitle}/><Field colors={colors} placeholder={config.detail} value={detail} onChange={setDetail}/>{needsAmount&&<Field colors={colors} placeholder={tool==="finance"?"Amount (Rs.)":tool==="labour"?"Wage (Rs.)":tool==="offers"?"Offered price per kg (Rs.)":"Cost / price (Rs.)"} value={amount} onChange={setAmount} numeric/>}{needsQuantity&&<Field colors={colors} placeholder="Quantity (kg)" value={quantity} onChange={setQuantity} numeric/>}<Field colors={colors} placeholder={config.extra} value={date} onChange={setDate}/><PrimaryButton colors={colors} label={config.button} onPress={async()=>{const cropTitle=title.trim();const taskDetail=detail;const taskDate=date;await create(config.kind);if(tool==="planting"&&cropTitle){await add({kind:"calendar",title:`Water and inspect ${cropTitle}`,detail:"Automatically created from crop-cycle record",date:taskDate||undefined});await add({kind:"calendar",title:`Fertilizer review: ${cropTitle}`,detail:"Check the crop stage and update the fertilizer schedule",date:taskDate||undefined});}if((tool==="calendar"||tool==="planting")&&taskDate){try{await Notifications.scheduleNotificationAsync({content:{title:cropTitle,body:taskDetail||"Farm task reminder"},trigger:{type:Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,seconds:2}});}catch{}}}}/><EntityList entities={list}/></ToolScroll>;
}
function assistantAnswer(question:string,language:string){const q=question.toLowerCase();const en=q.includes("price")?"Open Market Prices and compare the latest HARTI bulletin before choosing a buyer.":q.includes("rain")||q.includes("weather")?"Check the live weather screen and avoid spraying immediately before heavy rain.":"Record the crop, field condition, and date. For chemical treatment or disease diagnosis, confirm with your local agricultural officer.";if(language==="si")return "බෝගය, ක්ෂේත්‍ර තත්ත්වය සහ දිනය සටහන් කරන්න. රසායනික ප්‍රතිකාර හෝ රෝග විනිශ්චය සඳහා කෘෂිකර්ම නිලධාරියෙකුගෙන් තහවුරු කරගන්න.";if(language==="ta")return "பயிர், வயல் நிலை மற்றும் தேதியை பதிவு செய்யுங்கள். இரசாயன சிகிச்சை அல்லது நோய் கண்டறிதலுக்கு விவசாய அலுவலரிடம் உறுதி செய்யுங்கள்.";return en;}
function ToolScroll({children,colors}:{children:React.ReactNode;colors:any}){return <ScrollView style={{backgroundColor:colors.background}} contentContainerStyle={styles.content}>{children}</ScrollView>}
function Field({colors,placeholder,value,onChange,numeric}:{colors:any;placeholder:string;value:string;onChange:(v:string)=>void;numeric?:boolean}){return <TextInput style={[styles.field,{backgroundColor:colors.surface,color:colors.text,borderColor:colors.border}]} placeholder={placeholder} placeholderTextColor={colors.textMuted} value={value} onChangeText={onChange} keyboardType={numeric?"decimal-pad":"default"}/>}
function PrimaryButton({colors,label,onPress}:{colors:any;label:string;onPress:()=>void}){return <TouchableOpacity style={[styles.primary,{backgroundColor:colors.primary}]} onPress={onPress}><Text style={{color:colors.primaryContrast,fontWeight:"800"}}>{label}</Text></TouchableOpacity>}
function Info({colors,text}:{colors:any;text:string}){return <View style={[styles.info,{backgroundColor:colors.primarySoft}]}><MaterialCommunityIcons name="information-outline" size={20} color={colors.primary}/><Text style={[styles.body,{color:colors.textSecondary,flex:1}]}>{text}</Text></View>}
function Card({children,colors}:{children:React.ReactNode;colors:any}){return <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}>{children}</View>}
function Metric({colors,label,value}:{colors:any;label:string;value:string}){return <Card colors={colors}><Text style={[styles.sub,{color:colors.textMuted}]}>{label}</Text><Text style={[styles.cardTitle,{color:colors.text,marginTop:5}]}>{value}</Text></Card>}
function EntityList({entities,onRemove}:{entities:OfflineEntity[];onRemove?:(id:string)=>void}){const {theme}=useTheme();return <View style={{gap:8}}>{entities.length?entities.map(item=><View key={item.id} style={[styles.entity,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:theme.colors.text}]}>{item.title}</Text><Text style={[styles.sub,{color:theme.colors.textMuted}]}>{item.detail||item.date||item.kind} · {item.status}</Text></View>{onRemove&&<TouchableOpacity onPress={()=>onRemove(item.id)}><MaterialCommunityIcons name="delete-outline" size={20} color={theme.colors.danger}/></TouchableOpacity>}</View>):<Text style={[styles.sub,{color:theme.colors.textMuted,textAlign:"center",padding:20}]}>No records yet.</Text>}</View>}

const styles=StyleSheet.create({safe:{flex:1},header:{padding:16,flexDirection:"row",alignItems:"center",gap:12},title:{fontSize:20,fontWeight:"900"},sub:{fontSize:11,lineHeight:16},sync:{marginLeft:"auto",flexDirection:"row",gap:5,alignItems:"center",padding:9,borderRadius:10},content:{padding:16,paddingBottom:60,gap:12},offlineCard:{borderWidth:1,borderRadius:16,padding:16,flexDirection:"row",gap:12,alignItems:"center"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},tool:{width:"48%",borderWidth:1,borderRadius:16,padding:15,minHeight:140},icon:{width:45,height:45,borderRadius:13,alignItems:"center",justifyContent:"center",marginBottom:13},cardTitle:{fontSize:14,fontWeight:"800"},sectionTitle:{fontSize:17,fontWeight:"900",marginTop:8},field:{borderWidth:1,borderRadius:12,minHeight:48,paddingHorizontal:14,fontSize:13},primary:{minHeight:48,borderRadius:12,alignItems:"center",justifyContent:"center",padding:12},info:{padding:13,borderRadius:13,flexDirection:"row",gap:9,alignItems:"center"},body:{fontSize:12,lineHeight:18},card:{borderWidth:1,borderRadius:14,padding:15},entity:{borderWidth:1,borderRadius:12,padding:13,flexDirection:"row",alignItems:"center",gap:8},summary:{gap:8},photo:{width:"100%",height:230,borderRadius:16,resizeMode:"cover"}});
