const BASE=process.env.EXPO_PUBLIC_SPRING_BACKEND_URL??"http://127.0.0.1:8080";
export type TradeCollection="marketplace_listings"|"purchase_requests"|"trade_conversations"|"trade_messages"|"messages"|"offers"|"trade_orders"|"deliveries"|"payments"|"invoices"|"ratings"|"trusted_contacts"|"disputes"|"verification_requests";
export type TradeRecord={id:string;ownerId:string;ownerName:string;ownerRole:"farmer"|"buyer";title:string;detail?:string;crop?:string;quantity?:number;price?:number;location?:string;counterpartyId?:string;counterpartyName?:string;buyerId?:string;buyerName?:string;status?:string;createdAt?:string};
export type TradeContact={name?:string;email?:string;phoneNumber?:string;address?:string;region?:string};
export type TradeConversation={id:string;listingId:string;farmerId:string;farmerName:string;buyerId:string;buyerName:string;crop:string;listingTitle:string;listedQuantity?:number;listedPrice?:number;location?:string;status:"negotiating"|"awaiting_confirmation"|"agreed"|"cancelled";lastMessage?:string;updatedAt?:string;finalQuantity?:number;finalPrice?:number;totalAmount?:number;deliveryMethod?:string;deliveryDate?:string;agreedAt?:string;proposedBy?:string;farmerContact?:TradeContact;buyerContact?:TradeContact};
export type TradeMessage={id:string;conversationId:string;senderId:string;senderName:string;text:string;sentAt:string};
async function request<T>(path:string,options?:RequestInit){const response=await fetch(`${BASE}${path}`,options);if(!response.ok){let message=`Request failed (${response.status})`;try{const body=await response.json();message=body.message??message}catch{const body=await response.text();if(body)message=body}throw new Error(message)}return response.json() as Promise<T>}
export const getTradeRecords=(collection:TradeCollection)=>request<TradeRecord[]>(`/api/collections/${collection}`);
export const createTradeRecord=(collection:TradeCollection,payload:Omit<TradeRecord,"id">)=>request<{id:string}>(`/api/collections/${collection}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
export const updateTradeRecord=(collection:TradeCollection,id:string,payload:TradeRecord)=>request<{id:string}>(`/api/collections/${collection}/${encodeURIComponent(id)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
export const claimTradeListing=(listingId:string,buyerId:string,buyerName:string)=>request<TradeConversation>(`/api/trades/listings/${encodeURIComponent(listingId)}/claim`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({buyerId,buyerName})});
export const getUserTradeConversations=(userId:string)=>request<TradeConversation[]>(`/api/trades/user/${encodeURIComponent(userId)}`);
export const getTradeConversation=(listingId:string,userId:string)=>request<TradeConversation>(`/api/trades/${encodeURIComponent(listingId)}?userId=${encodeURIComponent(userId)}`);
export const getTradeMessages=(listingId:string,userId:string)=>request<TradeMessage[]>(`/api/trades/${encodeURIComponent(listingId)}/messages?userId=${encodeURIComponent(userId)}`);
export const sendTradeMessage=(listingId:string,payload:{senderId:string;senderName:string;text:string})=>request<TradeMessage>(`/api/trades/${encodeURIComponent(listingId)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
export const finalizeTrade=(listingId:string,payload:{userId:string;finalQuantity:number;finalPrice:number;deliveryMethod:string;deliveryDate:string})=>request<TradeConversation>(`/api/trades/${encodeURIComponent(listingId)}/finalize`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
export const cancelTradeDiscussion=(listingId:string,userId:string)=>request<{id:string;status:string}>(`/api/trades/${encodeURIComponent(listingId)}/cancel`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId})});
